version: '2.4'

services:
  cass:
    image: cassandra:3.11.8
    container_name: cass
    hostname: cass
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cass.yaml:/etc/cassandra/cass.yaml

networks:
  cassandra: