version: '3'
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - network1
    volumes:
      - ./ApiGateway/nginx.conf:/etc/nginx/nginx.conf
      - ./ApiGateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  user-service:
    image: user-service:compose_build
    build:
      context: ./UserService
      dockerfile: Dockerfile
    networks:
      - network1
    environment:
      PORT: ${USER_SERVICE_PORT}
      HOST: mongo
    restart: on-failure
    depends_on:
      - mongo
    links: 
      - mongo
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1



volumes:
   mongodata:

networks:
   network1:
