version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authdetailsdb
    volumes:
      - postgres_db_test:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_db_test: