version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    volumes:
      - ./ApiGateway/nginx.conf:/etc/nginx/nginx.conf
      - ./ApiGateway/api_gateway.conf:/etc/nginx/api_gateway.conf