version: '3'
services:
  neo4j:
    image: neo4j:4.0.3
    restart: unless-stopped
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/nistagram